package com.wiilog.wiistock.plugins.rfid.manager.exceptions;

public enum ZebraExceptionType {
    ACTION_INVALID,
    ACTION_REQUIRED,
    READER_ALREADY_CONNECTED,
    RETRIEVE_AVAILABLE_READERS_LIST_FAILURE,
    READER_CONNECTION_FAILURE,
    READER_CONNECTION_FAILURE_NOT_CONFIGURED,
    READER_CONNECTION_FAILURE_RFID_COMM_OPEN_ERROR,
    NO_READER_FOUND,
    READER_ALREADY_DISCONNECTED,
    READER_DISCONNECTION_FAILURE,
    READER_CONFIGURATION_FAILED,
    READER_NOT_CONNECTED,
    SCAN_STOP_FAILED,
    SCAN_STOP_FAILED_NO_INVENTORY_IN_PROGRESS,
    SCAN_START_FAILED,
    SCAN_START_FAILED_INVENTORY_ALREADY_IN_PROGRESS,
}
