name: Prepare build

inputs:
  KEYSTORE_JKS_PASSPHRASE:
    description: "Passphrase for decoding keystore.jks file"
    required: true
  GOOGLE_SERVICES_JSON_PASSPHRASE:
    description: "Passphrase for decoding google-services.json file"
    required: true
  KEYSTORE_PASSWORD:
    description: "The keystore password"
    required: true

runs:
  using: composite
  steps:
    - name: credential.ts.dist copy
      shell: sh
      run: cp src/environments/credentials.ts.dist src/environments/credentials.ts

    - name: Keystore creation
      shell: sh
      run: |
        touch android/app/keystore.jks
        gpg -d --passphrase ${{ inputs.KEYSTORE_JKS_PASSPHRASE }} --batch android/app/keystore.jks.asc > android/app/keystore.jks

    - name: google-services.json creation
      shell: sh
      run: |
        touch android/app/google-services.json
        gpg -d --passphrase ${{ inputs.GOOGLE_SERVICES_JSON_PASSPHRASE }} --batch android/app/google-services.json.asc > android/app/google-services.json

    - name: Keystore verification
      shell: sh
      run: keytool -list -v -keystore android/app/keystore.jks

    - name: keystore.properties creation
      shell: sh
      run: |
        cp android/app/keystore.properties.dist android/app/keystore.properties
        sed -i "s/keyPassword=/keyPassword=${{ inputs.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties
        sed -i "s/storePassword=/storePassword=${{ inputs.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties

    - name: Dependencies installation
      shell: sh
      run: yarn install
