export enum EmplacementScanModeEnum {
    TRACKING_PICK,
    TRACKING_DROP,
    TRACKING_EMPTY_ROUND,
    TRACKING_PICK_AND_DROP,
    STOCK_PICK,
    STOCK_DROP,
    STOCK_ASSOCIATION,
    DELIVERY_LOCATION,
    ARTICLE_CREATION,
    COLLECT_MANUAL,
}
