name: Build

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: wiilog/wiistock-mobile-app
            options: --user root

        steps:
            -   name: Checkout sources
                uses: actions/checkout@v1

            -   name: credential.ts.dist copy
                run: cp src/environments/credentials.ts.dist src/environments/credentials.ts

            -   name: Keystore creation
                run: |
                    touch android/app/keystore.jks &&
                    gpg -d --passphrase ${{ secrets.KEYSTORE_JKS_PASSPHRASE }} --batch android/app/keystore.jks.asc > android/app/keystore.jks

            -   name: google-services.json creation
                run: |
                    touch android/app/google-services.json &&
                    gpg -d --passphrase ${{ secrets.GOOGLE_SERVICES_JSON_PASSPHRASE }} --batch android/app/google-services.json.asc > android/app/google-services.json

            -   name: Keystore verification
                run: keytool -list -v -keystore android/app/keystore.jks

            -   name: keystore.properties creation
                run: |
                    cp android/app/keystore.properties.dist android/app/keystore.properties &&
                    sed -i "s/keyPassword=/keyPassword=${{ secrets.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties &&
                    sed -i "s/storePassword=/storePassword=${{ secrets.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties

            -   name: Dependencies installation
                run: yarn install

            -   name: Build FollowGT
                env:
                    APP_CUSTOM_NAME: "Follow GT"
                run: yarn gradle:assemble

            -   name: Apk copy
                run: cp android/app/build/outputs/apk/release/app-release.apk FollowGT.apk

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: FollowGT.apk
                    path: FollowGT.apk

            -   name: Upload on release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.ACCESS_TOKEN }}
                    file: FollowGT.apk
                    asset_name: FollowGT.apk
                    tag: ${{ github.ref }}

            -   name: Build wiistock
                env:
                    APP_CUSTOM_NAME: "Wiilog"
                run: yarn gradle assembleRelease

            -   name: Apk copy
                run: cp android/app/build/outputs/apk/release/app-release.apk Wiilog.apk

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: Wiilog.apk
                    path: Wiilog.apk

            -   name: Upload on release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.ACCESS_TOKEN }}
                    file: Wiilog.apk
                    asset_name: Wiilog.apk
                    tag: ${{ github.ref }}

            -   name: Build debug
                env:
                    APP_CUSTOM_NAME: "Follow GT"
                run: yarn gradle:assemble:debug

            -   name: Debug apk copy
                run: cp android/app/build/outputs/apk/debug/app-debug.apk FollowGT-debug.apk

            -   name: Upload debug artifact
                uses: actions/upload-artifact@v4
                with:
                    name: FollowGT-debug.apk
                    path: FollowGT-debug.apk

            -   name: Build debug
                env:
                    APP_CUSTOM_NAME: "Wiilog"
                run: yarn gradle assembleDebug

            -   name: Debug apk copy
                run: cp android/app/build/outputs/apk/debug/app-debug.apk Wiilog-debug.apk

            -   name: Upload debug artifact
                uses: actions/upload-artifact@v4
                with:
                    name: Wiilog-debug.apk
                    path: Wiilog-debug.apk

            -   name: Upload debug on release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.ACCESS_TOKEN }}
                    file: Wiilog-debug.apk
                    asset_name: Wiilog-debug.apk
                    tag: ${{ github.ref }}
