name: Build

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: wiilog/wiistock-mobile-app
            options: --user root

        steps:
            -   name: Checkout sources
                uses: actions/checkout@v1

            -   name: Copie credential.ts.dist
                run: cp src/environments/credentials.ts.dist src/environments/credentials.ts

            -   name: Creation du google-services.json
                run: |
                    touch android/app/google-services.json &&
                    echo "${{ secrets.GOOGLE_SERVICES_JSON }}" >> android/app/google-services.json | base64 -d > android/app/google-services.json

            -   name: Creation du keystore
                run: |
                    touch android/app/keystore.jks.asc &&
                    echo "${{ secrets.KEYSTORE_JKS }}" >> android/app/keystore.jks.asc | base64 --decode &&
                    touch android/app/keystore.jks &&
                    gpg -d --passphrase ${{ secrets.KEYSTORE_JKS_PASSPHRASE }} --batch android/app/keystore.jks.asc > android/app/keystore.jks

            -   name: verification du keystore
                run: keytool -list -v -keystore android/app/keystore.jks


            -   name: Creation du keystore.properties
                run: |
                    cp android/app/keystore.properties.dist android/app/keystore.properties &&
                    sed -i "s/keyPassword=/keyPassword=${{ secrets.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties &&
                    sed -i "s/storePassword=/storePassword=${{ secrets.KEYSTORE_PASSWORD }}/g" android/app/keystore.properties

            -   name: Instalation des dépendances
                run: yarn install

            -   name: Build
                run: yarn gradle:assemble

            -   name: Copie de l'apk
                run: cp android/app/build/outputs/apk/release/app-release.apk wiistock.apk

            -   name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: wiistock.apk
                    path: wiistock.apk

            -   name: Upload on release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.ACCESS_TOKEN }}
                    file: wiistock.apk
                    asset_name: wiistock.apk
                    tag: ${{ github.ref }}
